### PR TITLE
Simplify STM32 config

### PR DESCRIPTION
**Pull request by arnout**
The STM32 configs contain a lot of cruft that doesn't even exist on that SoC. Remove it from the kernel config.

There are still many peripheral chips enabled that don't exist on the -disco or -eval boards, but leave those in to make it easier for customers to get started with their own custom design.

### CODE REVIEW

**Comment by arnout** [comment]
Note: I haven't tested this on stm32p15-disco myself, but I've tested a similar change on our custom board.

**Comment by ricardosalveti** [comment]
Thanks for the changes, not related with the diff, but would you mind adding your git commit sign-off-by to your patches? You can do by running 'git commit -s --amend' on both commits.

**Comment by ricardosalveti** [comment]
Just to say that this is on my list, just need to test with a few different scenarios and build types (e.g. with display, wayland, etc).

I'm also planning on merging both disco and eval in order to simplify, as suggested by your commit.

**Review by MrCry0 — APPROVED** [review]
Nice. LGTM. Not tested.

**Comment by ricardosalveti** [comment]
Closing as this is now part of https://github.com/foundriesio/lmp-kernel-cache/pull/71 (includes a merge from both board fragments).

**Pull request closed without merging**
