### PR TITLE
linux-v5.15.y: fix issues, warnings, dups, etc. and remove unused options

### PR DESCRIPTION
**Pull request by MrCry0**
Some work to forward port improves from 5.10 to 5.15.

In testing...

- imx8mm - **OK**
- imx6ull - **OK**

 **NOTES**

- imx8mm requires these changes to boot properly. Otherwise, it reboots by a watchdog.

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
LGTM, thanks for doing this pr, I also noted a lot of warnings when building locally.

Did you boot test to see if the board is still working as expected? Just because sometimes disabling an option can cause bad side effects.

**Comment by MrCry0** [comment]
Not yet, I converted it to draft until test booting.

**Review by Tim-Anderson — APPROVED** [review]
LGTM so far

**Comment by ricardosalveti** [comment]
Nice, thanks for all the cleaning effort here.

**Pull request merged**
