### PR TITLE
bsp: imx: add initial bsp definition for imx6ulevk

### PR DESCRIPTION
**Pull request by mike-scott**
Setup kernel fragments for i.MX6UL-EVK.  This is mostly a copy from
i.MX6ULL-EVK, except CAAM is specifically disabled (which doesn't
exist on i.MX6ULL SoC).  CAAM is used in OP-TEE.

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
@ricardosalveti Once approved, I can pull this into the 5.10 and master branches

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]
LGTM

**Pull request merged**
