### PR TITLE
5.10 pci cleanups

### PR DESCRIPTION
**Pull request by mike-scott**
Commit a172480e805e ("bsp: imx: enable DesignWare PCI host platform")
erroneously enabled PCIE_DW_PLAT_HOST which causes 2 drivers to use
the same resources.  This causes a hang on related HW.

For imx8mqevk we can also drop manual selection of PCIE_DW.  This is
automatically included as a part of the PCI_IMX6_HOST configuration.

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
Verified on:
- imx8mm-lpddr4-evk (reva)
- imx8mq-evk
- imx8mp-lpddr4-evk

**Comment by MrCry0** [comment]
Verified on:
* apalis-ixm8
* imx8mm-lpddr4-evk (revb) (w/o link, no pcie hw available)
* apalis-imx6 (w/o link, no pcie hw available)

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM, I will push the same changes to 5.15 and master.

**Pull request merged**
