### PR TITLE
bsp: imx: imx8mn-evk: add support for i.MX8M Nano EVK

### PR DESCRIPTION
**Pull request by mike-scott**
These settings started from the 5.10-2.1.x-imx kernel and options
that weren't specific to the hardware were mostly removed.

This process can be delicate so there are some left over configs
which were questionable.

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM, please mirror into the 5.15 and master branches once merged.

**Review by angolini — APPROVED** [review]

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]
LGTM

**Comment by mike-scott** [comment]
> LGTM, please mirror into the 5.15 and master branches once merged.

Done.

**Pull request merged**
