### PR TITLE
bsp: stm32: rename stm32mp1 config files

### PR DESCRIPTION
**Pull request by igoropaniuk**
Rename stm32mp1->stm32mp15, so it corresponds to the new naming in
meta-st-stm32mp layer.

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

### CODE REVIEW

**Comment by ricardosalveti** [comment]
I think we can just backport https://github.com/foundriesio/lmp-kernel-cache/commit/5903ae3c9cf5201a4dd0dccb331f3ac5ddc7228f from master, which was done in 5.10 and master only.

**Comment by igoropaniuk** [comment]
@ricardosalveti but that commit doesn't include rename of `stm32mp15-disco.scc` and `stm32mp15-disco.cfg` (same for -eval), which imho is better for consistency

**Comment by ricardosalveti** [comment]
@igoropaniuk +1, mind then doing the rename at master and backporting both to 5.15? Just to be aligned.

**Comment by MrCry0** [comment]
@igoropaniuk We need to keep the legacy config names in order we use these machines with this version of kernel in previous yocto releases prior to kirkstone. Machines were renamed in kirkstone version of stm layer only.

**Comment by ricardosalveti** [comment]
I think it is fine to remove the older ones for master and 5.15, as older releases are all using 5.10 (which has both).

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request closed without merging**
