### PR TITLE
Linux v5.15.y:  Adds jailhouse features

### PR DESCRIPTION
**Pull request by quaresmajose**
backported from https://github.com/foundriesio/lmp-kernel-cache/pull/86

Signed-off-by: Jose Quaresma jose.quaresma@foundries.io

### CODE REVIEW

**Review by MrCry0 — COMMENTED** [review]
Please, make a PR to master. Then we backport the feature to 5.15 and 5.10.

**Comment by quaresmajose** [comment]
When my tests finish https://github.com/foundriesio/lmp-manifest/pull/291 I can do it and submit the first one to the master branch.
Thanks

**Comment by quaresmajose** [comment]
@MrCry0 master PR https://github.com/foundriesio/lmp-kernel-cache/pull/86 open and ready to be reviewed.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
